version: "3.9"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - my_network

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - my_network

  mongoDB:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: tbl
    networks:
      - my_network

  persistence:
    image: persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    container_name: persistence-service
    depends_on:
      - db
      - mongoDB
      - kafka
    networks:
      - my_network
    working_dir: /fileio
    volumes:
      - ./:/fileio:xro

  core:
    image: core:0.1.0-SNAPSHOT
    ports:
      - "8082:8082"
    container_name: core-service
    depends_on:
      - persistence
      - kafka
    networks:
      - my_network

  ui:
    image: ui:0.1.0-SNAPSHOT
    stdin_open: true
    tty: true
    container_name: ui-service
    depends_on:
      - core
      - kafka
    networks:
      - my_network
    environment:
      DISPLAY: $DISPLAY

  ui2:
    image: ui:0.1.0-SNAPSHOT
    stdin_open: true
    tty: true
    container_name: ui-service2
    depends_on:
      - core
      - kafka
    networks:
      - my_network
    environment:
      DISPLAY: $DISPLAY

networks:
  my_network:
