version: "3.9"

services:
  persistence:
    image: persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    container_name: persistence-service
    networks:
      - my_network

  core:
    image: core:0.1.0-SNAPSHOT
    ports:
      - "8082:8082"
    container_name: core-service
    depends_on:
      - persistence
    networks:
      - my_network
    environment:
      - PERSISTENCE_HOST=persistence
      - PERSISTENCE_PORT=8081

  ui:
    image: ui:0.1.0-SNAPSHOT
    stdin_open: true
    tty: true
    container_name: ui-service
    depends_on:
      - core
    networks:
      - my_network
    environment:
      - CORE_HOST=core
      - CORE_PORT=8082

networks:
  my_network:
